---

- name: Java - download package
  get_url:
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"
    url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz
    dest: /tmp
    mode: 0755

- name: Java - create root directory
  file: path=/opt/jdk state=directory mode=0755 owner=root group=root

- name: Java - install package
  unarchive: src=/tmp/jdk-8u121-linux-x64.tar.gz dest=/opt/jdk

- name: Java - set alternative for java
  command: "update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_121/bin/java 100"

- name: Java - set alternative for javac
  command: "update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_121/bin/javac 100"
  
- name: Java - set JAVA_HOME
  lineinfile: dest=/etc/environment regexp="^JAVA_HOME=" line="JAVA_HOME=/opt/jdk/jdk1.8.0_121"
  
