---

- name: fill index - check port
  wait_for:
    host: 172.17.0.2
    port: 9200

- name: Verify ES cluster
  uri:
    url: http://172.17.0.2:9200
  register: uri_cluster
  until: uri_cluster.status == 200
  retries: 5
  delay: 30

- name: Verify index
  uri:
    url: http://172.17.0.2:9200/gemini
    method: HEAD
  register: uri_index
  failed_when: not (uri_index.status == 200 or uri_index.status == 404)
  
- name: Create index
  uri:
    url: http://172.17.0.2:9200/gemini
    method: PUT
    body_format: json
    body: '{"settings": {"number_of_shards": 3 , "number_of_replicas": 1}}'
  when: uri_index.status == 404
  
- name: Add document
  uri:
    url: http://172.17.0.2:9200/gemini/content
    method: POST
    body_format: json
    body: '{"field1": "{{ item }}", "field2": "same value"}'
  with_items:
    - "one"
    - "two"
    - "three"
    - "four"
    - "five"
  register: uri_document
  failed_when: uri_document.status != 201
 
 
