---

- name: Verify index
  uri:
    url: http://172.17.0.2:9200/gemini
    method: HEAD
  register: index
  failed_when: index.status != 200 or index.status != 404
  
- name: Create index
  uri:
    url: http://172.17.0.2:9200/gemini
    method: PUT
    body_format: json
    body: '{"settings": {"number_of_shards": 3 , "number_of_replicas": 1}}'
  when: index.status == 404
  
- name: Add document
  uri:
    url: http://172.17.0.2:9200/gemini/content
    method: POST
    body_format: json
    body: '{"field1": "{{ item }}", "field2": "same value"}'
  with_items:
    - "one"
    - "two"
    - "three"
    - "four"
    - "five"
  register: document
  failed_when: document.status != 201
 
 
